name: Python CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout repo
        uses: actions/checkout@v2

      - name: Step 2 - Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Step 3 - Run code
        run: |
          python3 test.py
          
      - name: Step 4 - check output
        run: |
          output=$(python3 test.py)
          echo "Output was: $output"
          if [[ "$output" == 2 ]]; then
            echo "✅ Output is OK"
            exit 0
          else
            echo "❌ Output is NOT OK"
            exit 1
          fi
